network:
  version: 2
  ethernets:
    NM-9030d344-a059-412c-aa85-ffa2526e3d73:
      renderer: NetworkManager
      match:
        name: "enp8s0"
      addresses:
      - "192.168.249.1/30"
      wakeonlan: true
      networkmanager:
        uuid: "9030d344-a059-412c-aa85-ffa2526e3d73"
        name: "turret-direct-ethernet"
        passthrough:
          connection.autoconnect-priority: "100"
          ethernet._: ""
          ipv4.ignore-auto-dns: "true"
          ipv4.never-default: "true"
          ipv6.addr-gen-mode: "default"
          ipv6.ignore-auto-dns: "true"
          ipv6.method: "link-local"
          ipv6.never-default: "true"
          ipv6.ip6-privacy: "-1"
          proxy._: ""
