"""Structural hardware boundary used by the common backend policies.

Implementations own I/O; the controller owns target/loss/aiming/lifecycle rules.
Workers exchange completed results via worker_protocol, never motor commands.
"""
from typing import Any, Protocol


class CameraDevice(Protocol):
    def status(self) -> dict[str, Any]: ...
    def wait_for_frame(self, after: int = 0, timeout: float = 1) -> Any: ...
    def wait_for_sample(self, previous_sequence: int, timeout: float, after: float = 0.0) -> Any: ...


class MotorDevice(Protocol):
    def status(self) -> dict[str, Any]: ...
    def sample_pose(self, captured_at: float | None = None) -> dict | None: ...
    def arm(self) -> None: ...
    def disable(self) -> None: ...
    def recalibrate(self) -> None: ...
    def move(self, axis: str, degrees: float) -> None: ...
    def point(self, goals: dict[str, float]) -> dict: ...
    def track(self, offsets: dict[str, float]) -> dict: ...


class DetectionSource(Protocol):
    model: str
    def status(self) -> dict[str, Any]: ...
    def set_model(self, model: str) -> None: ...
    def set_prompts(self, prompts: list[str]) -> None: ...
    def selection(self, revision: int, sequence: int, instance_id: int) -> dict: ...
    def frame_version(self) -> Any: ...
    def wait_for_update(self, version: Any, timeout: float) -> Any: ...
